export type PortfolioCategory = {
  slug: string;
  label: string;
  shortLabel: string;
  intro: string;
  customerAngle: string;
};

export type PortfolioWork = {
  slug: string;
  title: string;
  client: string;
  categorySlug: string;
  metric: string;
  platform: string;
  blurb: string;
  thumbnail: string;
  reelUrl?: string;
  sample?: boolean;
};

export const portfolioCategories: PortfolioCategory[] = [
  { slug: "healthcare", label: "Healthcare", shortLabel: "Health", intro: "Specialist-led content that keeps medical expertise clear, careful, and human.", customerAngle: "" },
  { slug: "beauty", label: "Beauty & Aesthetics", shortLabel: "Beauty", intro: "Beauty, grooming, and aesthetic clients turned into repeatable on-camera authority.", customerAngle: "" },
  { slug: "automotive", label: "Automotive", shortLabel: "Auto", intro: "High-consideration detailing and mobility brands built on founder trust.", customerAngle: "" },
  { slug: "home", label: "Home & Living", shortLabel: "Home", intro: "Everyday home, cleaning, and build expertise made genuinely watchable.", customerAngle: "" },
  { slug: "pet", label: "Pet", shortLabel: "Pet", intro: "Warm, expert pet content where care, credibility, and personality meet.", customerAngle: "" },
  { slug: "finance", label: "Finance", shortLabel: "Finance", intro: "Finance and business education shaped for clarity and repeat viewing.", customerAngle: "" },
  { slug: "lifestyle", label: "Lifestyle & Retail", shortLabel: "Lifestyle", intro: "Retail, food, and lifestyle creators with formats made to be shared.", customerAngle: "" },
];

export const portfolioWorks: PortfolioWork[] = [
  {
    slug: "rehabilitation-drliang",
    title: "問問梁醫師",
    client: "@rehabilitation_drliang",
    categorySlug: "healthcare",
    metric: "123K followers",
    platform: "3.2M top reel",
    blurb: "",
    thumbnail: "/images/case-2.jpg",
    reelUrl: "https://www.instagram.com/reel/C24nMruvWNO/",
  },
  {
    slug: "dr-frankshen",
    title: "沈耿仲醫師",
    client: "@dr.frankshen",
    categorySlug: "healthcare",
    metric: "40K followers",
    platform: "805K top reel",
    blurb: "",
    thumbnail: "/images/case-5.jpg",
    reelUrl: "https://www.instagram.com/reel/DGnMP3_ssgx/",
  },
  {
    slug: "binbinmomtalks",
    title: "緻為醫療",
    client: "@binbinmomtalks",
    categorySlug: "healthcare",
    metric: "20K followers",
    platform: "451K top reel",
    blurb: "",
    thumbnail: "/images/case-6.jpg",
    reelUrl: "https://www.instagram.com/reel/DXyk5jJjSi2/",
  },
  {
    slug: "dr-yincheng",
    title: "鄭穎醫師",
    client: "@dr.yincheng",
    categorySlug: "healthcare",
    metric: "16K followers",
    platform: "334K top reel",
    blurb: "",
    thumbnail: "/images/case-3.jpg",
    reelUrl: "https://www.instagram.com/reel/DWGwH_YCau6/",
  },
  {
    slug: "dr-tsen-vision",
    title: "悦光眼科診所",
    client: "@dr.tsen_vision",
    categorySlug: "healthcare",
    metric: "712 followers",
    platform: "131K top reel",
    blurb: "",
    thumbnail: "/images/case-8.jpg",
    reelUrl: "https://www.instagram.com/reel/DVlEDXwkV14/",
  },
  {
    slug: "pskin1998-tw",
    title: "彭賢禮",
    client: "@pskin1998.tw",
    categorySlug: "healthcare",
    metric: "4K followers",
    platform: "125K top reel",
    blurb: "",
    thumbnail: "/images/case-7.jpg",
    reelUrl: "https://www.instagram.com/reel/DWQ1rvbCDGl/",
  },
  {
    slug: "drwekinc",
    title: "陳威智醫生",
    client: "@drwekinc",
    categorySlug: "healthcare",
    metric: "8K followers",
    platform: "119K top reel",
    blurb: "",
    thumbnail: "/images/case-4.jpg",
    reelUrl: "https://www.instagram.com/reel/DWaN4SzE9yr/",
  },
  {
    slug: "crazysophiahsu",
    title: "許書華醫師",
    client: "@crazysophiahsu",
    categorySlug: "healthcare",
    metric: "50K followers",
    platform: "65K top reel",
    blurb: "",
    thumbnail: "/images/case-9.jpg",
    reelUrl: "https://www.instagram.com/reel/DZXUgdUgRmC/",
  },
  {
    slug: "akiko017",
    title: "過期空姐KIKO",
    client: "@akiko017",
    categorySlug: "beauty",
    metric: "155K followers",
    platform: "3.6M top reel",
    blurb: "",
    thumbnail: "/images/case-10.jpg",
    reelUrl: "https://www.instagram.com/reel/Cwr13UHvr1f/",
  },
  {
    slug: "timo6uan9",
    title: "直男先生Timo",
    client: "@timo6uan9",
    categorySlug: "beauty",
    metric: "101K followers",
    platform: "2.2M top reel",
    blurb: "",
    thumbnail: "/images/case-11.jpg",
    reelUrl: "https://www.instagram.com/reel/C-cfrAthSfS/",
  },
  {
    slug: "cherry-queen77",
    title: "愛美教主七七",
    client: "@cherry_queen77",
    categorySlug: "beauty",
    metric: "173K followers",
    platform: "994K top reel",
    blurb: "",
    thumbnail: "/images/case-12.jpg",
    reelUrl: "https://www.instagram.com/reel/DOywVX0Emhl/",
  },
  {
    slug: "miss-beautytw",
    title: "BTL素人",
    client: "@miss.beautytw",
    categorySlug: "beauty",
    metric: "1K followers",
    platform: "75K top reel",
    blurb: "",
    thumbnail: "/images/case-13.jpg",
    reelUrl: "https://www.instagram.com/reel/DYzKkgLAKuC/",
  },
  {
    slug: "dir-white-",
    title: "myBRA",
    client: "@dir.white_",
    categorySlug: "beauty",
    metric: "78 followers",
    platform: "4K top reel",
    blurb: "",
    thumbnail: "/images/case-14.jpg",
    reelUrl: "https://www.instagram.com/reel/DUAvpSqgcik/",
  },
  {
    slug: "kwax-kevin",
    title: "KEVIn大大",
    client: "@kwax_kevin",
    categorySlug: "automotive",
    metric: "173K followers",
    platform: "5.0M top reel",
    blurb: "",
    thumbnail: "/images/case-15.jpg",
    reelUrl: "https://www.instagram.com/reel/DPLtwLiDesu/",
  },
  {
    slug: "kwax-taiwan",
    title: "K-WAX",
    client: "@kwax_taiwan",
    categorySlug: "automotive",
    metric: "74K followers",
    platform: "947K top reel",
    blurb: "",
    thumbnail: "/images/case-2.jpg",
    reelUrl: "https://www.instagram.com/reel/DaHYpiKgGZM/",
  },
  {
    slug: "funte-tw",
    title: "Funte",
    client: "@funte_tw",
    categorySlug: "automotive",
    metric: "3K followers",
    platform: "550K top reel",
    blurb: "",
    thumbnail: "/images/case-3.jpg",
    reelUrl: "https://www.instagram.com/reel/DXb1Bj-Ej1s/",
  },
  {
    slug: "bert-chao",
    title: "小趙老闆",
    client: "@bert.chao",
    categorySlug: "home",
    metric: "84K followers",
    platform: "9.4M top reel",
    blurb: "",
    thumbnail: "/images/case-5.jpg",
    reelUrl: "https://www.instagram.com/reel/DXWrjJrPW-8/",
  },
  {
    slug: "sheng0432",
    title: "笙闆",
    client: "@sheng0432",
    categorySlug: "home",
    metric: "99K followers",
    platform: "6.3M top reel",
    blurb: "",
    thumbnail: "/images/case-4.jpg",
    reelUrl: "https://www.instagram.com/reel/C5QiIuIvvfw/",
  },
  {
    slug: "cleanclean-tw",
    title: "淨淨",
    client: "@cleanclean.tw",
    categorySlug: "home",
    metric: "24K followers",
    platform: "5.9M top reel",
    blurb: "",
    thumbnail: "/images/case-7.jpg",
    reelUrl: "https://www.instagram.com/reel/DEhZzJyI2G2/",
  },
  {
    slug: "linchi20240510",
    title: "凌際建築",
    client: "@linchi20240510",
    categorySlug: "home",
    metric: "4K followers",
    platform: "139K top reel",
    blurb: "",
    thumbnail: "/images/case-8.jpg",
    reelUrl: "https://www.instagram.com/reel/DUdLdn0lZEO/",
  },
  {
    slug: "mosi-out",
    title: "黑蚊滾",
    client: "@mosi_out",
    categorySlug: "home",
    metric: "8K followers",
    platform: "102K top reel",
    blurb: "",
    thumbnail: "/images/case-9.jpg",
    reelUrl: "https://www.instagram.com/reel/DXyystYjPaV/",
  },
  {
    slug: "building-hyl",
    title: "華友聯",
    client: "@building.hyl",
    categorySlug: "home",
    metric: "15K followers",
    platform: "95K top reel",
    blurb: "",
    thumbnail: "/images/case-6.jpg",
    reelUrl: "https://www.instagram.com/reel/DRBZ5Evkdj-/",
  },
  {
    slug: "dogcat-boss-nohair",
    title: "汪喵的光頭老闆",
    client: "@dogcat.boss.nohair",
    categorySlug: "pet",
    metric: "124K followers",
    platform: "5.3M top reel",
    blurb: "",
    thumbnail: "/images/case-11.jpg",
    reelUrl: "https://www.instagram.com/reel/DFNSXF-JdYI/",
  },
  {
    slug: "dr-birdscience",
    title: "鳥科學_顧芳瑜醫師",
    client: "@dr.birdscience",
    categorySlug: "pet",
    metric: "59K followers",
    platform: "2.8M top reel",
    blurb: "",
    thumbnail: "/images/case-10.jpg",
    reelUrl: "https://www.instagram.com/reel/DAa3lgLg3TS/",
  },
  {
    slug: "chisin-animal-hospital-",
    title: "琪欣動物醫院",
    client: "@chisin_animal_hospital_",
    categorySlug: "pet",
    metric: "11K followers",
    platform: "378K top reel",
    blurb: "",
    thumbnail: "/images/case-12.jpg",
    reelUrl: "https://www.instagram.com/reel/DZxEd11iYsq/",
  },
  {
    slug: "mj-lin1095",
    title: "MJ老師",
    client: "@mj_lin1095",
    categorySlug: "finance",
    metric: "24K followers",
    platform: "2.2M top reel",
    blurb: "",
    thumbnail: "/images/case-13.jpg",
    reelUrl: "https://www.instagram.com/reel/DTAe1J0FeFv/",
  },
  {
    slug: "finance-mjlin09",
    title: "超級數字力",
    client: "@finance_mjlin09",
    categorySlug: "finance",
    metric: "11K followers",
    platform: "3K top reel",
    blurb: "",
    thumbnail: "/images/case-14.jpg",
    reelUrl: "https://www.instagram.com/reel/DQ_lkFSiao9/",
  },
  {
    slug: "sharonpengtw",
    title: "雪倫的隱藏版生活",
    client: "@sharonpengtw",
    categorySlug: "lifestyle",
    metric: "207K followers",
    platform: "2.2M top reel",
    blurb: "",
    thumbnail: "/images/case-2.jpg",
    reelUrl: "https://www.instagram.com/reel/DY6x8GoDUhh/",
  },
  {
    slug: "hi-anwei",
    title: "偶然占心",
    client: "@hi_anwei",
    categorySlug: "lifestyle",
    metric: "23K followers",
    platform: "1.2M top reel",
    blurb: "",
    thumbnail: "/images/case-7.jpg",
    reelUrl: "https://www.instagram.com/reel/DYE7L7DCmN9/",
  },
  {
    slug: "xiaokeyunlin",
    title: "小可",
    client: "@xiaokeyunlin",
    categorySlug: "lifestyle",
    metric: "20K followers",
    platform: "1.2M top reel",
    blurb: "",
    thumbnail: "/images/case-5.jpg",
    reelUrl: "https://www.instagram.com/reel/DXq3a5XCNO3/",
  },
  {
    slug: "meikao-love5520",
    title: "Mei錢也要買",
    client: "@meikao_love5520",
    categorySlug: "lifestyle",
    metric: "222K followers",
    platform: "1.1M top reel",
    blurb: "",
    thumbnail: "/images/case-4.jpg",
    reelUrl: "https://www.instagram.com/reel/DZE90dUgawr/",
  },
  {
    slug: "ginaholictw",
    title: "NISORO",
    client: "@ginaholictw",
    categorySlug: "lifestyle",
    metric: "50K followers",
    platform: "1.1M top reel",
    blurb: "",
    thumbnail: "/images/case-11.jpg",
    reelUrl: "https://www.instagram.com/reel/C6pv1WPJLQe/",
  },
  {
    slug: "wenkunai",
    title: "超老闆",
    client: "@wenkunai",
    categorySlug: "lifestyle",
    metric: "116K followers",
    platform: "731K top reel",
    blurb: "",
    thumbnail: "/images/case-9.jpg",
    reelUrl: "https://www.instagram.com/reel/DDrofO6zOGz/",
  },
  {
    slug: "mizz-eisen",
    title: "佑青",
    client: "@mizz_eisen",
    categorySlug: "lifestyle",
    metric: "11K followers",
    platform: "639K top reel",
    blurb: "",
    thumbnail: "/images/case-10.jpg",
    reelUrl: "https://www.instagram.com/reel/DVimXO6EehW/",
  },
  {
    slug: "ga12life",
    title: "黃金甲",
    client: "@ga12life",
    categorySlug: "lifestyle",
    metric: "13K followers",
    platform: "562K top reel",
    blurb: "",
    thumbnail: "/images/case-6.jpg",
    reelUrl: "https://www.instagram.com/reel/DXrLNWKDK07/",
  },
  {
    slug: "seles-storytelling",
    title: "鴻鼎菓子",
    client: "@seles_storytelling",
    categorySlug: "lifestyle",
    metric: "34K followers",
    platform: "529K top reel",
    blurb: "",
    thumbnail: "/images/case-3.jpg",
    reelUrl: "https://www.instagram.com/reel/DJB6FbDqZJ3/",
  },
  {
    slug: "leo-mikoguitar",
    title: "米可吉他",
    client: "@leo.mikoguitar",
    categorySlug: "lifestyle",
    metric: "1K followers",
    platform: "165K top reel",
    blurb: "",
    thumbnail: "/images/case-8.jpg",
    reelUrl: "https://www.instagram.com/reel/DSCeA_MAcqN/",
  },
  {
    slug: "zach-chung",
    title: "襪子叔叔_阿誠",
    client: "@zach_chung",
    categorySlug: "lifestyle",
    metric: "7K followers",
    platform: "124K top reel",
    blurb: "",
    thumbnail: "/images/case-15.jpg",
    reelUrl: "https://www.instagram.com/reel/DYO81nhJ5Vs/",
  },
];

export function getPortfolioCategory(slug: string) {
  return portfolioCategories.find((category) => category.slug === slug);
}

export function getPortfolioWorksByCategory(slug: string) {
  return portfolioWorks.filter((work) => work.categorySlug === slug);
}

export function getPortfolioCategoryCount(slug: string) {
  return getPortfolioWorksByCategory(slug).length;
}

export function getPortfolioCategoryPath(slug: string) {
  return `/our-portfolio/${slug}`;
}
